# GitHub Discussions categories config
# Requires GitHub Discussions to be enabled on the repository.

categories:
  - name: Q&A
    description: Ask questions and get help from the community
    emoji: ❓
    is_answerable: true

  - name: Ideas
    description: Share and discuss new ideas for BlueSphere
    emoji: 💡
    is_answerable: false

  - name: Announcements
    description: Official updates and announcements
    emoji: 📢
    is_answerable: false
