name-template: 'BlueSphere v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ✨ Features
    labels: ['feature', 'enhancement']
  - title: 🐛 Fixes
    labels: ['bug', 'fix']
  - title: 🧪 Tests
    labels: ['testing']
  - title: 📚 Docs
    labels: ['documentation']
  - title: 🛠 Chores
    labels: ['chore', 'ci']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '\<>`*_{}'
version-resolver:
  major:
    labels: ['semver:major']
  minor:
    labels: ['semver:minor']
  patch:
    labels: ['semver:patch']
  default: patch
template: |
  ## What’s Changed
  $CHANGES

  ## Links
  - Full Changelog: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$NEXT_TAG
