# SPDX-License-Identifier: MIT
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bluesphere}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bluesphere}
      POSTGRES_DB: ${POSTGRES_DB:-bluesphere}
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    ports: ["8080:8080"]
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped
volumes:
  db_data:
