services:
  - type: web
    name: bluesphere-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn simple_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"

  - type: web
    name: bluesphere-webapp
    env: node
    buildCommand: cd frontend/ocean-ui && npm install && npm run build
    startCommand: cd frontend/ocean-ui && npm start
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"

  - type: web
    name: bluesphere-website
    env: node
    buildCommand: cd frontend/bluesphere-site && npm install && npm run build
    startCommand: cd frontend/bluesphere-site && npm start
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"

databases:
  - name: bluesphere-db
    databaseName: bluesphere
    user: bluesphere_user