---
title: "Announcement: <highlight>"
labels: []
about: Share a news update with the community
body:
  - type: markdown
    attributes:
      value: |
        Use this template for project updates and community news.
  - type: input
    id: headline
    attributes:
      label: Headline
      placeholder: e.g., BlueSphere v1.0 — Public Beta is Live!
      description: A clear announcement headline
      validations:
        required: true
  - type: textarea
    id: content
    attributes:
      label: Details
      placeholder: What's new, why it matters, what's next
