blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation & FAQ
    url: https://github.com/twick1234/BlueSphere/wiki
    about: Check our documentation and frequently asked questions
  - name: 💬 Community Discussions
    url: https://github.com/twick1234/BlueSphere/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/twick1234/BlueSphere/security/advisories/new
    about: Privately report security vulnerabilities
  - name: 📧 Direct Contact
    url: mailto:team@bluesphere.org
    about: Contact the BlueSphere team directly for sensitive matters