name: CI (Node & Playwright)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  website-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: frontend/bluesphere-site
        run: |
          npm ci || npm install
          npx playwright install --with-deps
      - name: Build website
        working-directory: frontend/bluesphere-site
        run: npm run build
      - name: Start website (background)
        working-directory: frontend/bluesphere-site
        run: npm start &
      - name: Run E2E tests
        run: npm run test:e2e
