name: Daily Smart Ingestion

on:
  schedule:
    # 02:00 SGT daily (UTC 18:00)
    - cron: '0 18 * * *'
  workflow_dispatch:

concurrency:
  group: smart-ingestion
  cancel-in-progress: false

jobs:
  ingest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dataset: [ndbc, argo, ersst, currents]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary requests

      - name: Run dataset ingestion (with retry)
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        run: |
          set -e
          DATASET="${{ matrix.dataset }}"
          SCRIPT="ingestion/ingest_${DATASET}.py"
          if [ "$DATASET" = "ersst" ]; then SCRIPT="ingestion/ingest_ersst.py"; fi

          echo "Running $SCRIPT"
          n=0
          until [ $n -ge 3 ]
          do
            python "$SCRIPT" && break
            n=$((n+1))
            sleep $(( 15 * n ))  # exponential-ish backoff
          done

      - name: Post-run status
        if: always()
        run: echo "Dataset ${{ matrix.dataset }} run finished with status ${{ job.status }}"
