name: Setup Discussions

on:
  workflow_dispatch:

jobs:
  setup-discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure discussions and categories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/setup_discussions.sh Twick1234 BlueSphere
